#PBS -l nodes=1:nehalem:ppn=8
#PBS -l walltime=00:50:00
#PBS -l mem=24gb
#PBS -N psum_openmp_8cpu
#PBS -S /bin/bash
#PBS -j oe
#

## Some job preprocessing may go here
export OMP_NUM_THREADS=8

# $PBS_O_WORKDIR is the directory from which the job was submitted
cd $PBS_O_WORKDIR

./psum_openmp 1000000000 1

# output from the runs will be in psum_openmp_4cpu.o####
# where #### is the job id.
#---------------- end of job file --------------------------
